server:
  port: 8081

master:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mall?characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    initialSize: 0
    maxActive: 16
    minIdle: 1
    maxWait: 60000
    #打开PSCache，并且指定每个连接PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    #通过connectionProperties属性来打开mergeSql功能；慢SQL记录
    #connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

    #配置间隔多久启动一次DestroyThread，对连接池内的连接才进行一次检测，单位是毫秒。
      #检测时:1.如果连接空闲并且超过minIdle以外的连接，如果空闲时间超过minEvictableIdleTimeMillis设置的值则直接物理关闭。2.在minIdle以内的不处理
    timeBetweenEvictionRunsMillis: 60000
    #配置一个连接在池中最大空闲时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 from dual
    #设置从连接池获取连接时是否检查连接有效性，true时，如果连接空闲时间超过minEvictableIdleTimeMillis进行检查，否则不检查;false时，不检查
    testWhileIdle: true
    #是否在获得连接后检测其可用性
    testOnBorrow: false
    #是否在连接放回连接池后检测其可用性
    testOnReturn: false

slaver1:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mall?characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    initialSize: 0
    maxActive: 16
    minIdle: 1
    maxWait: 60000
    #打开PSCache，并且指定每个连接PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    #通过connectionProperties属性来打开mergeSql功能；慢SQL记录
    #connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 from dual
    #是否在连接空闲一段时间后检测其可用性
    testWhileIdle: true
    #是否在获得连接后检测其可用性
    testOnBorrow: false
    #是否在连接放回连接池后检测其可用性
    testOnReturn: false

slaver2:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mall?characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    initialSize: 0
    maxActive: 16
    minIdle: 1
    maxWait: 60000
    #打开PSCache，并且指定每个连接PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    #通过connectionProperties属性来打开mergeSql功能；慢SQL记录
    #connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 from dual
    #是否在连接空闲一段时间后检测其可用性
    testWhileIdle: true
    #是否在获得连接后检测其可用性
    testOnBorrow: false
    #是否在连接放回连接池后检测其可用性
    testOnReturn: false

spring:
  #  通过上面的master和slaver自定义数据源
  #  datasource:
  #    type: com.alibaba.druid.pool.DruidDataSource
  #    druid:
  #      driver-class-name: com.mysql.cj.jdbc.Driver
  #      url: jdbc:mysql://127.0.0.1:3306/mall?characterEncoding=utf8&serverTimezone=Asia/Shanghai
  #      username: root
  #      password: 123456
  #      initialSize: 0
  #      maxActive: 16
  #      minIdle: 1
  #      maxWait: 60000
  #      #打开PSCache，并且指定每个连接PSCache的大小
  #      poolPreparedStatements: true
  #      maxPoolPreparedStatementPerConnectionSize: 20
  #      #通过connectionProperties属性来打开mergeSql功能；慢SQL记录
  #      #connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  #      timeBetweenEvictionRunsMillis: 60000
  #      minEvictableIdleTimeMillis: 300000
  #      validationQuery: select 1 from dual
  #      #是否在连接空闲一段时间后检测其可用性
  #      testWhileIdle: true
  #      #是否在获得连接后检测其可用性
  #      testOnBorrow: false
  #      #是否在连接放回连接池后检测其可用性
  #      testOnReturn: false
  #配置监控统计拦截的filters，去掉后监控界面sql将无法统计,'wall'用于防火墙
  #      filters: stat, wall, log4j
  redis:
    #    database: 0
    #    host: 127.0.0.1
    #    port: 6379
    #    password: 123456
    cluster:
      nodes:
        - 127.0.0.1:7001
        - 127.0.0.1:7002
        - 127.0.0.1:7003
        - 127.0.0.1:7004
        - 127.0.0.1:7005
        - 127.0.0.1:7006
      max-redirects: 3  # 获取失败 最大重定向次数
    timeout: 6000
    lettuce:
      pool:
        max-active: 16
        max-wait: -1
        max-idle: 8
        min-idle: 1
  #ElasticSearch
  data:
    elasticsearch:
      repositories:
        enabled: true
      cluster-nodes: 127.0.0.1:9300 # es的连接地址及端口号
      cluster-name: elasticsearch # es集群的名称
  rabbitmq:
    host: localhost # rabbitmq的连接地址
    port: 5672 # rabbitmq的连接端口号
    virtual-host: /mall # rabbitmq的虚拟host
    username: mall # rabbitmq的用户名
    password: mall # rabbitmq的密码
    publisher-confirm-type: simple # rabbitmq的密码

  main:
    allow-bean-definition-overriding: true # 某个bug
logging:
  level:
    net:
      man:
        mapper: DEBUG
secretKey: ZGFpbWxlcg==
#mybatis-plus:
#  mapper-locations: classpath*:mapper/*/*.xml
#  type-aliases-package: com.man.entity