server:
  port: 8081
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mall?characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    #最大活跃数
    maxActive: 16
    #初始化数量
    initialSize: 1
    #最大连接等待超时时间
    maxWait: 60000
    #打开PSCache，并且指定每个连接PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    #通过connectionProperties属性来打开mergeSql功能；慢SQL记录
    #connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    #配置监控统计拦截的filters，去掉后监控界面sql将无法统计,'wall'用于防火墙
    filters: stat, wall, log4j
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
    timeout: 6000
    lettuce:
      pool:
        max-active: 16
        max-wait: -1
        max-idle: 8
        min-idle: 1
  #ElasticSearch
  data:
    elasticsearch:
      repositories:
        enabled: true
      cluster-nodes: 127.0.0.1:9300 # es的连接地址及端口号
      cluster-name: elasticsearch # es集群的名称
  rabbimq:
    host: localhost # rabbitmq的连接地址
    port: 5672 # rabbitmq的连接端口号
    virtual-host: /mall # rabbitmq的虚拟host
    username: mall # rabbitmq的用户名
    password: mall # rabbitmq的密码
    publisher-confirms-type: true #如果对异步消息需要回调必须设置为true
  main:
    allow-bean-definition-overriding: true # 某个bug
logging:
  level:
    net:
      man:
        mapper: DEBUG
secretKey: ZGFpbWxlcg==
mybatis-plus:
  mapper-locations: classpath*:mapper/*/*.xml
  type-aliases-package: net.man.entity